// Server Component: the research programme, read-only.
//
// Source: lib/research-data.json, generated by
//   python csp_screener/backtest/export_research.py
// That script reads the study output files directly. No number on this page
// is typed by hand, and nothing here touches Supabase or the paper record.

import research from '@/lib/research-data.json';

export const metadata = { title: 'Research — CSP Screener' };

type Arm = {
  label: string; value: number; unit: string; n: number;
  max_dd_pct: number | null; is_control: boolean;
};

function money(a: Arm) {
  const v = a.unit === '%' ? `${a.value.toFixed(1)}%` : `$${a.value.toFixed(2)}`;
  return a.value >= 0 ? `+${v}` : v.replace('-', '−');
}

// Literal class strings only — Tailwind's JIT scans source text, so an
// interpolated `text-${tone}` is never generated and would render as default.
const TONE = {
  text: 'text-text',
  danger: 'text-danger',
  success: 'text-success',
  warning: 'text-warning',
} as const;

function Stat({ label, value, tone = 'text', sub }: {
  label: string; value: string; tone?: keyof typeof TONE; sub?: string;
}) {
  return (
    <div className="bg-panel border border-border rounded-lg p-4">
      <div className="text-xs text-muted uppercase tracking-wide font-medium">{label}</div>
      <div className={`mt-2 text-3xl font-semibold ${TONE[tone]}`}>{value}</div>
      {sub && <div className="mt-1 text-xs text-muted">{sub}</div>}
    </div>
  );
}

export default function ResearchPage() {
  const { totals, structural, amendments, in_progress, generated } = research as any;
  const toll = structural?.round_trip_toll ?? [];
  const decay = (structural?.signal_horizon_decay ?? []).filter(
    (d: any) => d.window === 'valid'
  );
  const single = toll.find((t: any) => t.universe === 'single names');
  const index = toll.find((t: any) => t.universe === 'index ETFs');

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold">Research</h1>
        <p className="text-sm text-muted mt-1">
          The pre-registered backtest programme on 8 years of purchased options
          data — what was tested, what it cost, and what survived.
        </p>
      </div>

      {/* ── The headline. This is the number that matters. ─────────────── */}
      <div className="rounded-lg border border-danger/40 bg-danger/5 p-5">
        <div className="text-lg font-semibold">
          No configuration has survived validation.
        </div>
        <p className="text-sm text-muted mt-2 max-w-3xl">
          Every strategy family tested so far — selling premium, buying premium,
          buying volatility, and plain stock rules — has come back negative once
          real friction and out-of-sample validation are applied. The paper
          track record on the other tabs is <strong className="text-text">process
          discipline, not evidence of an edge</strong>. Reaching the 200-trade
          go-live gate would not change that.
        </p>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Stat label="Configurations run" value={String(totals.configs_run)} />
        <Stat label="Logged runs" value={String(totals.runs_logged)}
              sub="the multiplicity denominator" />
        <Stat label="Promoted to validation"
              value={String(amendments.reduce((s: number, a: any) => s + a.promoted, 0))} />
        <Stat label="Survivors" value={String(totals.survivors)} tone="danger" />
      </div>

      {/* ── Why. The two measurements that explain all of it. ──────────── */}
      <section>
        <h2 className="text-lg font-semibold">Why none of it worked</h2>
        <p className="text-sm text-muted mt-1 max-w-3xl">
          Not the signals — the toll. Measured on the purchased data, matched on
          delta, days-to-expiry and open interest.
        </p>

        {toll.length > 0 && (
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-sm border border-border rounded-lg overflow-hidden">
              <thead className="bg-panel text-muted text-xs uppercase tracking-wide">
                <tr>
                  <th className="text-left px-4 py-2 font-medium">Universe</th>
                  <th className="text-right px-4 py-2 font-medium">Median spread</th>
                  <th className="text-right px-4 py-2 font-medium">On a mid of</th>
                  <th className="text-right px-4 py-2 font-medium">Round-trip toll</th>
                </tr>
              </thead>
              <tbody className="font-mono">
                {toll.map((t: any) => (
                  <tr key={t.universe} className="border-t border-border">
                    <td className="px-4 py-2 font-sans">{t.universe}</td>
                    <td className="px-4 py-2 text-right">${t.median_spread.toFixed(2)}</td>
                    <td className="px-4 py-2 text-right">${t.median_mid.toFixed(2)}</td>
                    <td className={`px-4 py-2 text-right font-semibold ${
                      t.round_trip_pct_of_premium > 10 ? 'text-danger' : 'text-warning'}`}>
                      {t.round_trip_pct_of_premium.toFixed(1)}% of premium
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <div className="mt-4 grid md:grid-cols-2 gap-4">
          <div className="rounded-lg border border-border bg-panel p-4">
            <div className="text-xs text-muted uppercase tracking-wide font-medium">
              The toll vs the prize
            </div>
            <p className="text-sm mt-2">
              The variance risk premium — the entire edge available in options —
              is worth roughly <strong>3–5% a month</strong>.
              {single && (
                <> On single names the toll is <strong className="text-danger">
                {single.round_trip_pct_of_premium.toFixed(1)}%</strong>, three to four times
                the whole prize. That is why option <em>buyers</em> and{' '}
                <em>sellers</em> both lost: both were paying the same market maker.</>
              )}
              {index && (
                <> Index ETFs cost <strong className="text-warning">
                {index.round_trip_pct_of_premium.toFixed(1)}%</strong> — {(
                  single ? (single.round_trip_pct_of_premium /
                            index.round_trip_pct_of_premium).toFixed(1) : '—')}× cheaper.</>
              )}
            </p>
          </div>
          <div className="rounded-lg border border-border bg-panel p-4">
            <div className="text-xs text-muted uppercase tracking-wide font-medium">
              Buying volatility loses before friction
            </div>
            <p className="text-sm mt-2">
              With slippage set to zero — entering at the ask, exiting at the bid,
              $1 per leg only — an index straddle still returns{' '}
              <strong className="text-danger">−$37 a trade</strong>. The premium
              is real and the buyer pays it. Friction deepens the loss; it does
              not cause it.
            </p>
          </div>
        </div>
      </section>

      {/* ── The bar, and the signal that cannot clear it. ──────────────── */}
      {decay.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold">The one real signal, and why it is not enough</h2>
          <p className="text-sm text-muted mt-1 max-w-3xl">
            Stocks at a 52-week high underperform — the only effect that held out
            of sample. A bought option needs roughly <strong className="text-text">
            2.5–3% a month</strong> to overcome time decay. This signal produces
            about 1.3%, and only for 21 days. Validation window shown.
          </p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-sm border border-border rounded-lg overflow-hidden">
              <thead className="bg-panel text-muted text-xs uppercase tracking-wide">
                <tr>
                  <th className="text-left px-4 py-2 font-medium">Horizon</th>
                  <th className="text-right px-4 py-2 font-medium">Edge per month</th>
                  <th className="text-right px-4 py-2 font-medium">p-value</th>
                  <th className="text-left px-4 py-2 font-medium">Reading</th>
                </tr>
              </thead>
              <tbody className="font-mono">
                {decay.map((d: any) => {
                  const alive = d.p < 0.01 && d.edge_pct_per_month < 0;
                  return (
                    <tr key={d.horizon_days} className="border-t border-border">
                      <td className="px-4 py-2">{d.horizon_days}d</td>
                      <td className={`px-4 py-2 text-right font-semibold ${
                        alive ? 'text-accent' : 'text-muted'}`}>
                        {d.edge_pct_per_month > 0 ? '+' : '−'}
                        {Math.abs(d.edge_pct_per_month).toFixed(2)}%
                      </td>
                      <td className="px-4 py-2 text-right text-muted">
                        {d.p < 0.001 ? d.p.toExponential(0) : d.p.toFixed(2)}
                      </td>
                      <td className="px-4 py-2 font-sans text-muted">
                        {alive ? 'real and strong'
                          : d.edge_pct_per_month > 0 ? 'sign flips — gone'
                          : 'indistinguishable from zero'}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <p className="text-xs text-muted mt-2 max-w-3xl">
            This is why long-dated options (LEAPS) were ruled out without buying
            any data: a one-year option would have been bought to capture
            something that does not exist at that tenor.
          </p>
        </section>
      )}

      {/* ── Every amendment. ───────────────────────────────────────────── */}
      <section>
        <h2 className="text-lg font-semibold">Every test run</h2>
        <p className="text-sm text-muted mt-1 max-w-3xl">
          &ldquo;Best on search window&rdquo; is the top cell out of many on the
          training data — it is the maximum of N draws and is{' '}
          <strong className="text-warning">search noise, not a result</strong>.
          The columns that matter are Promoted and Validated.
        </p>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-sm border border-border rounded-lg overflow-hidden">
            <thead className="bg-panel text-muted text-xs uppercase tracking-wide">
              <tr>
                <th className="text-left px-3 py-2 font-medium">#</th>
                <th className="text-left px-3 py-2 font-medium">What it asked</th>
                <th className="text-left px-3 py-2 font-medium">Instrument</th>
                <th className="text-right px-3 py-2 font-medium">Cells</th>
                <th className="text-right px-3 py-2 font-medium">Best on search</th>
                <th className="text-right px-3 py-2 font-medium">Its control</th>
                <th className="text-right px-3 py-2 font-medium">Promoted</th>
                <th className="text-right px-3 py-2 font-medium">Validated</th>
              </tr>
            </thead>
            <tbody>
              {amendments.map((a: any) => (
                <tr key={a.id} className="border-t border-border align-top">
                  <td className="px-3 py-3 font-mono text-muted whitespace-nowrap">{a.id}</td>
                  <td className="px-3 py-3">
                    <div className="font-medium">{a.title}</div>
                    <div className="text-xs text-muted mt-0.5">{a.question}</div>
                  </td>
                  <td className="px-3 py-3 text-muted text-xs">
                    {a.instrument}<br />
                    <span className="opacity-70">{a.universe}</span>
                  </td>
                  <td className="px-3 py-3 text-right font-mono">{a.n_configs}</td>
                  <td className="px-3 py-3 text-right font-mono text-muted">
                    {money(a.best_on_search_window)}
                    {a.best_on_search_window.max_dd_pct != null && (
                      <div className="text-xs opacity-60">
                        dd {a.best_on_search_window.max_dd_pct}%
                      </div>
                    )}
                  </td>
                  <td className="px-3 py-3 text-right font-mono text-muted">
                    {a.control ? money(a.control) : '—'}
                    {a.beat_control === false && (
                      <div className="text-xs text-danger">lost to control</div>
                    )}
                  </td>
                  <td className="px-3 py-3 text-right font-mono">{a.promoted}</td>
                  <td className={`px-3 py-3 text-right font-mono font-semibold ${
                    a.validated > 0 ? 'text-success' : 'text-danger'}`}>
                    {a.validated}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── What is still open. ────────────────────────────────────────── */}
      {in_progress && (
        <section className="rounded-lg border border-accent/40 bg-accent/5 p-5">
          <div className="flex items-baseline gap-2 flex-wrap">
            <span className="text-xs font-mono text-accent">
              AMENDMENT {in_progress.id}
            </span>
            <span className="font-semibold">{in_progress.title}</span>
          </div>
          <p className="text-sm text-muted mt-2 max-w-3xl">{in_progress.why}</p>
          <div className="mt-3 flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted">
            <span>Status: <span className="text-text">{in_progress.status}</span></span>
            <span>Declared before the data exists: <span className="text-text">
              {in_progress.declared_prediction}</span></span>
          </div>
        </section>
      )}

      <p className="text-xs text-muted">
        {research.isolation_note} Generated {new Date(generated).toLocaleString()} by{' '}
        <span className="font-mono">export_research.py</span>. Full pre-registration
        and per-amendment verdicts live in{' '}
        <span className="font-mono">csp_screener/backtest/MANIFEST.md</span>.
      </p>
    </div>
  );
}
